server:
  port: 8001
spring:
  application:
    name: shortlink-project
  datasource:
#        username: root
#        password: 123456
#        url: jdbc:mysql://192.168.88.128:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        hikari:
#          connection-test-query: select 1
#          connection-timeout: 20000
#          idle-timeout: 300000
#          maximum-pool-size: 5
#          minimum-idle: 5
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      host: 192.168.88.128
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.128:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: http://common-rocketmq-dev.magestack.cn:9876
  producer:
    group: short-link_project-service_stats-save_pg_mtf1115
    topic: short-link_project-service_topic_mtf1115
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg_mtf1115