server:
  port: 8001
spring:
  datasource:
#        username: root
#        password: 123456
#        url: jdbc:mysql://192.168.88.128:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        hikari:
#          connection-test-query: select 1
#          connection-timeout: 20000
#          idle-timeout: 300000
#          maximum-pool-size: 5
#          minimum-idle: 5
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      host: 192.168.88.128
      port: 6379
      password: 123456
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml